### ISSUE TITLE
字符集不全啊！

### ISSUE THREAD

**Issue by xiezi5160** [chick-soups/TextFilesForTextMeshPro#3]
西班牙语的字符好像有些纰漏~

**Comment by chick-soups** [comment]
哪些字符不全？我对西班牙语不太熟悉

**Comment by xiezi5160** [comment]
[百度百科](https://baike.baidu.com/item/%E8%A5%BF%E7%8F%AD%E7%89%99%E8%AF%AD/398390?fr=aladdin)
百度百科里面有些补充，我对西语也不是很熟悉，只是之前有用过您的这个开源项目，发现西语的字符有很多没有，才给您反馈的；
比如，重音标志的字母á、é、í、ó和ú。一些西语特有的符号。
<html>
<body>


符号 | 西班牙语 | 汉语 | 例句
-- | -- | -- | --
, | la coma | 逗号 | Ella es ana,es china.
: | dos puntos | 冒号 | Agua: es una sustancia
" " | las comillas | 引号 | Él dijo: "Yo también estoy aquí".
. | el punto | 句号 | Soy estudiante.
¿....? | la interrogación | 问号（成对，在句子首尾） | ¿Cómo te llamas?
¡....! | la admiración | 叹号（成对，在句子首尾） | ¡Mucho gusto!
ü | la diéresis | 分音号（字母U上面的两点） | 略
－ | la raya, el guión largo o corto | 破折号 | 略
（ ） | el paréntesis | 圆括号 | 略
[ ] | los corchetes | 方括号 | 略


</body>
</html>

**Comment by h824612113** [comment]
韩语的字符不全，我现在用静态字体+动态字体了，没有的会是个方块

**Comment by chick-soups** [comment]
> [百度百科](https://baike.baidu.com/item/%E8%A5%BF%E7%8F%AD%E7%89%99%E8%AF%AD/398390?fr=aladdin) 百度百科里面有些补充，我对西语也不是很熟悉，只是之前有用过您的这个开源项目，发现西语的字符有很多没有，才给您反馈的； 比如，重音标志的字母á、é、í、ó和ú。一些西语特有的符号。
> 
> 符号	西班牙语	汉语	例句
> ,	la coma	逗号	Ella es ana,es china.
> :	dos puntos	冒号	Agua: es una sustancia
> " "	las comillas	引号	Él dijo: "Yo también estoy aquí".
> .	el punto	句号	Soy estudiante.
> ¿....?	la interrogación	问号（成对，在句子首尾）	¿Cómo te llamas?
> ¡....!	la admiración	叹号（成对，在句子首尾）	¡Mucho gusto!
> ü	la diéresis	分音号（字母U上面的两点）	略
> －	la raya, el guión largo o corto	破折号	略
> （ ）	el paréntesis	圆括号	略
> [ ]	los corchetes	方括号	略
谢谢反馈，我近期会更新上去。

**Comment by chick-soups** [comment]
> 韩语的字符不全，我现在用静态字体+动态字体了，没有的会是个方块

有哪些不全的，麻烦罗列一下。谢谢。

**Comment by chick-soups** [comment]
> 韩语的字符不全，我现在用静态字体+动态字体了，没有的会是个方块

我更新了韩语的demo，你再看看。

**Comment by chick-soups** [comment]
> [百度百科](https://baike.baidu.com/item/%E8%A5%BF%E7%8F%AD%E7%89%99%E8%AF%AD/398390?fr=aladdin) 百度百科里面有些补充，我对西语也不是很熟悉，只是之前有用过您的这个开源项目，发现西语的字符有很多没有，才给您反馈的； 比如，重音标志的字母á、é、í、ó和ú。一些西语特有的符号。
> 
> 符号	西班牙语	汉语	例句
> ,	la coma	逗号	Ella es ana,es china.
> :	dos puntos	冒号	Agua: es una sustancia
> " "	las comillas	引号	Él dijo: "Yo también estoy aquí".
> .	el punto	句号	Soy estudiante.
> ¿....?	la interrogación	问号（成对，在句子首尾）	¿Cómo te llamas?
> ¡....!	la admiración	叹号（成对，在句子首尾）	¡Mucho gusto!
> ü	la diéresis	分音号（字母U上面的两点）	略
> －	la raya, el guión largo o corto	破折号	略
> （ ）	el paréntesis	圆括号	略
> [ ]	los corchetes	方括号	略

我更新了西班牙语的demo,你再看看。
